<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K1275IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K127_5I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K127_5I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'camion' => ['privates', '.errored..service_locator.K127_5I.App\\Entity\\Camion', NULL, 'Cannot autowire service ".service_locator.K127_5I": it needs an instance of "App\\Entity\\Camion" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'camion' => 'App\\Entity\\Camion',
            'entityManager' => '?',
        ]);
    }
}
