<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QdkfewIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qdkfewI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qdkfewI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contributionRepository' => ['privates', 'App\\Repository\\ContributionRepository', 'getContributionRepositoryService', true],
        ], [
            'contributionRepository' => 'App\\Repository\\ContributionRepository',
        ]);
    }
}
