<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WZwGqEXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WZwGqEX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WZwGqEX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fournisseurRepository' => ['privates', 'App\\Repository\\FournisseurRepository', 'getFournisseurRepositoryService', true],
        ], [
            'fournisseurRepository' => 'App\\Repository\\FournisseurRepository',
        ]);
    }
}
