<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AKL1mJkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AKL1mJk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AKL1mJk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contribution' => ['privates', '.errored..service_locator.AKL1mJk.App\\Entity\\Contribution', NULL, 'Cannot autowire service ".service_locator.AKL1mJk": it needs an instance of "App\\Entity\\Contribution" but this type has been excluded in "config/services.yaml".'],
        ], [
            'contribution' => 'App\\Entity\\Contribution',
        ]);
    }
}
