<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RalIsqiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RalIsqi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RalIsqi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fournisseur' => ['privates', '.errored..service_locator.RalIsqi.App\\Entity\\Fournisseur', NULL, 'Cannot autowire service ".service_locator.RalIsqi": it needs an instance of "App\\Entity\\Fournisseur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'fournisseur' => 'App\\Entity\\Fournisseur',
        ]);
    }
}
