<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KXeZZIFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kXeZZIF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kXeZZIF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'projet' => ['privates', '.errored..service_locator.kXeZZIF.App\\Entity\\Projet', NULL, 'Cannot autowire service ".service_locator.kXeZZIF": it needs an instance of "App\\Entity\\Projet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'projet' => 'App\\Entity\\Projet',
        ]);
    }
}
