<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FHt_MjjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fHt.Mjj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fHt.Mjj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depenseProjet' => ['privates', '.errored..service_locator.fHt.Mjj.App\\Entity\\DepenseProjet', NULL, 'Cannot autowire service ".service_locator.fHt.Mjj": it needs an instance of "App\\Entity\\DepenseProjet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'depenseProjet' => 'App\\Entity\\DepenseProjet',
        ]);
    }
}
