<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RIJHbUjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rIJHbUj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rIJHbUj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'signalementRepository' => ['privates', 'App\\Repository\\SignalementRepository', 'getSignalementRepositoryService', true],
        ], [
            'signalementRepository' => 'App\\Repository\\SignalementRepository',
        ]);
    }
}
