<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CGFOjppService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CGFOjpp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CGFOjpp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'zoneDeCollecte' => ['privates', '.errored..service_locator.CGFOjpp.App\\Entity\\ZoneDeCollecte', NULL, 'Cannot autowire service ".service_locator.CGFOjpp": it needs an instance of "App\\Entity\\ZoneDeCollecte" but this type has been excluded in "config/services.yaml".'],
        ], [
            'zoneDeCollecte' => 'App\\Entity\\ZoneDeCollecte',
        ]);
    }
}
