<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCamion3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yaw31Fu.App\Entity\Camion' shared service.
     *
     * @return \App\Entity\Camion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yaw31Fu": it needs an instance of "App\\Entity\\Camion" but this type has been excluded in "config/services.yaml".');
    }
}
