<?php

namespace ContainerWyvko4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepenseProjetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fHt.Mjj.App\Entity\DepenseProjet' shared service.
     *
     * @return \App\Entity\DepenseProjet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fHt.Mjj": it needs an instance of "App\\Entity\\DepenseProjet" but this type has been excluded in "config/services.yaml".');
    }
}
