security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: plaintext  # ⚠️ Only use this in dev

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            stateless: false
            logout:
                path: app_logout

            # Two-Factor Section
            two_factor:
                auth_form_path: 2fa_login           # Route name for the 2FA form
                check_path: 2fa_login_check         # Route that processes the code
                default_target_path: homepage       # Where to go after success
                always_use_default_target_path: true

    access_control:
        - { path: ^/dashboard, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: plaintext
