<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UdGUJXoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UdGUJXo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UdGUJXo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projet' => ['privates', '.errored..service_locator.UdGUJXo.App\\Entity\\Projet', NULL, 'Cannot autowire service ".service_locator.UdGUJXo": it needs an instance of "App\\Entity\\Projet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'projet' => 'App\\Entity\\Projet',
        ]);
    }
}
