<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2IkNt8dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2IkNt8d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2IkNt8d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projetRepository' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService', true],
        ], [
            'projetRepository' => 'App\\Repository\\ProjetRepository',
        ]);
    }
}
