<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y1YYVxEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y1YYVxE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y1YYVxE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'signalement' => ['privates', '.errored..service_locator.Y1YYVxE.App\\Entity\\Signalement', NULL, 'Cannot autowire service ".service_locator.Y1YYVxE": it needs an instance of "App\\Entity\\Signalement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'signalement' => 'App\\Entity\\Signalement',
        ]);
    }
}
