<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2gi5SKUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2gi5SKU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2gi5SKU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depenseProjetRepository' => ['privates', 'App\\Repository\\DepenseProjetRepository', 'getDepenseProjetRepositoryService', true],
        ], [
            'depenseProjetRepository' => 'App\\Repository\\DepenseProjetRepository',
        ]);
    }
}
