<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N8I90xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n8_i90x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n8_i90x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'camionRepository' => ['privates', 'App\\Repository\\CamionRepository', 'getCamionRepositoryService', true],
        ], [
            'camionRepository' => 'App\\Repository\\CamionRepository',
        ]);
    }
}
