<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ILUMgGRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iLUMgGR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iLUMgGR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contribution' => ['privates', '.errored..service_locator.iLUMgGR.App\\Entity\\Contribution', NULL, 'Cannot autowire service ".service_locator.iLUMgGR": it needs an instance of "App\\Entity\\Contribution" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'contribution' => 'App\\Entity\\Contribution',
            'entityManager' => '?',
        ]);
    }
}
