<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WEF5ozcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WEF5ozc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WEF5ozc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'camion' => ['privates', '.errored..service_locator.WEF5ozc.App\\Entity\\Camion', NULL, 'Cannot autowire service ".service_locator.WEF5ozc": it needs an instance of "App\\Entity\\Camion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'camion' => 'App\\Entity\\Camion',
        ]);
    }
}
