<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I6Eo_QHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i6Eo.qH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i6Eo.qH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'signalement' => ['privates', '.errored..service_locator.i6Eo.qH.App\\Entity\\Signalement', NULL, 'Cannot autowire service ".service_locator.i6Eo.qH": it needs an instance of "App\\Entity\\Signalement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'signalement' => 'App\\Entity\\Signalement',
        ]);
    }
}
