<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContributionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AKL1mJk.App\Entity\Contribution' shared service.
     *
     * @return \App\Entity\Contribution
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AKL1mJk": it needs an instance of "App\\Entity\\Contribution" but this type has been excluded in "config/services.yaml".');
    }
}
