<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kXeZZIF.App\Entity\Projet' shared service.
     *
     * @return \App\Entity\Projet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kXeZZIF": it needs an instance of "App\\Entity\\Projet" but this type has been excluded in "config/services.yaml".');
    }
}
