<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignalement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.i6Eo.qH.App\Entity\Signalement' shared service.
     *
     * @return \App\Entity\Signalement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.i6Eo.qH": it needs an instance of "App\\Entity\\Signalement" but this type has been excluded in "config/services.yaml".');
    }
}
