<?php

namespace ContainerIyAMfVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZoneDeCollecte2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MuvVkWx.App\Entity\ZoneDeCollecte' shared service.
     *
     * @return \App\Entity\ZoneDeCollecte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MuvVkWx": it needs an instance of "App\\Entity\\ZoneDeCollecte" but this type has been excluded in "config/services.yaml".');
    }
}
