<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLQxILrW\App_KernelMDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLQxILrW/App_KernelMDebugContainer.php') {
    touch(__DIR__.'/ContainerLQxILrW.legacy');

    return;
}

if (!\class_exists(App_KernelMDebugContainer::class, false)) {
    \class_alias(\ContainerLQxILrW\App_KernelMDebugContainer::class, App_KernelMDebugContainer::class, false);
}

return new \ContainerLQxILrW\App_KernelMDebugContainer([
    'container.build_hash' => 'LQxILrW',
    'container.build_id' => 'faf6ae64',
    'container.build_time' => 1743777082,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLQxILrW');
